### PR TITLE
Added German Translation

### PR DESCRIPTION
**Pull request by maxeckel**
Hello Yarob,

i added a german translation.

### CODE REVIEW

**Comment by EazyServer** [comment]
Hi Max,

Thanks for you PR. can you please incorporate your changes to language dropdown in [Header.vue](https://github.com/EazyServer/Vue-Bootstrap-Calendar/blob/master/src/Components/Header.vue) 

Can you also squash your commits.

**Comment by maxeckel** [comment]
Sorry forgot to push the Header change :D

Alright, Header is updated and commits are squashed

**Comment by EazyServer** [comment]
Thanks for that.

I just pulled your changes locally. I can see the changes but it's not showing on the demo example!
As last step, you will need to run `npm run build` on terminal after you finish. That should build all dists needed.

You can also use `npm run dev` while developing 

So,  can you please do that and squash again?

Everything else looks great. Cheers

**Comment by maxeckel** [comment]
Forgot that again -.- sorry 
In the b4 Branch i added an watch Script so i can't forget :D 
In about half an hour i'll add the dists

**Comment by maxeckel** [comment]
Dist files are updated and squashed

**Comment by EazyServer** [comment]
Thanks very much.

One last small change. can you please change the version to `1.3.2` on [package.json](https://github.com/EazyServer/Vue-Bootstrap-Calendar/blob/master/package.json) so I can push to NPM.

**Comment by maxeckel** [comment]
I'm about to open a pull request for the "Add Event" Form/Modal.

Maybe we could add that to 1.3.2 too, if you approve.

When that pull request is opened i start work on migrate the i18n fix from my B4 branch. That could go to 1.3.2 too

**Comment by EazyServer** [comment]
I don't think that would be a good idea! crumbing loads of different size changes into one minor revision number!

I think your language addition is a minor revision i.e. `1.3.*`
Add Even/Form modal is a medium revision change i.e.  `1.*.*`
**i18n** fix could be a medium reversion too, so is B4 migration. That said, we could also set this as complete new version , as you suggested earlier, i.e. `2.*.*`, to help github users chose between supported Bootstraps versions.

**Comment by maxeckel** [comment]
Alright, lets do it like that.

I'll update the version

**Comment by maxeckel** [comment]
Version updated to 1.3.2

**Pull request merged**
